/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Dell
 */
import java.lang.System.*;
import java.lang.System.Logger.Level;
import java.sql.*;
import javax.swing.JOptionPane;
import java.text.SimpleDateFormat;
import java.sql.SQLException;
import java.sql.ResultSet;
import java.sql.DriverManager;
import java.util.Vector;
import javax.swing.table.DefaultTableModel;
public class Patient extends javax.swing.JFrame {
Connection con=null;
ResultSet rs=null;
PreparedStatement pst=null;
table ta = new table();

    /**
     * Creates new form Dashboard
     */
    public Patient() {
        initComponents();
        ta.updateTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        p = new javax.swing.JTextField();
        n = new javax.swing.JTextField();
        a = new javax.swing.JTextField();
        e = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        t = new javax.swing.JTextField();
        g = new javax.swing.JComboBox<>();
        jScrollPane1 = new javax.swing.JScrollPane();
        T = new javax.swing.JTable();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        D = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED, null, null, null, new java.awt.Color(0, 0, 0)));

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 255));
        jLabel1.setText("Family Dental Care");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(51, 51, 255));
        jLabel2.setText("Admin panel");

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel3.setText("Patient");
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });

        jLabel4.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel4.setText("Appointment");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel6.setText("Staff");
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });

        jLabel7.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel7.setText("Doctor");
        jLabel7.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel7MouseClicked(evt);
            }
        });

        jLabel8.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel8.setText("Room");
        jLabel8.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel8MouseClicked(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel9.setText("Payment");
        jLabel9.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel9MouseClicked(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 0, 0));
        jLabel10.setText("Logout");
        jLabel10.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel10MouseClicked(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(15, 15, 15)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel7)
                            .addComponent(jLabel6)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3)
                            .addComponent(jLabel1)
                            .addComponent(jLabel8)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(30, 30, 30)
                        .addComponent(jLabel2)))
                .addContainerGap(14, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addGap(47, 47, 47)
                .addComponent(jLabel3)
                .addGap(34, 34, 34)
                .addComponent(jLabel4)
                .addGap(38, 38, 38)
                .addComponent(jLabel6)
                .addGap(37, 37, 37)
                .addComponent(jLabel7)
                .addGap(44, 44, 44)
                .addComponent(jLabel8)
                .addGap(43, 43, 43)
                .addComponent(jLabel9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 95, Short.MAX_VALUE)
                .addComponent(jLabel10)
                .addContainerGap())
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 513));

        jLabel11.setFont(new java.awt.Font("Bell MT", 1, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(0, 153, 153));
        jLabel11.setText("Manage Patient");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 10, 181, -1));

        jLabel12.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel12.setText("Patient ID");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 78, -1, -1));

        jLabel13.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel13.setText("Name");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 127, -1, -1));

        jLabel14.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel14.setText("Address");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 170, -1, -1));

        jLabel15.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel15.setText("Date of Birth");
        getContentPane().add(jLabel15, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 278, -1, -1));

        jLabel16.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel16.setText("NIC No");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, -1, -1));

        jLabel17.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel17.setText("Telephone No");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 180, -1, -1));

        jLabel18.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel18.setText("Age");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 80, -1, -1));

        jLabel19.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        jLabel19.setText("Gender");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 228, -1, -1));

        p.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                pActionPerformed(evt);
            }
        });
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 73, 103, 31));
        getContentPane().add(n, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 122, 103, 30));
        getContentPane().add(a, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 170, 103, 35));
        getContentPane().add(e, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 87, 28));
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 120, 87, 28));
        getContentPane().add(t, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 170, 87, 31));

        g.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Male", "Female" }));
        getContentPane().add(g, new org.netbeans.lib.awtextra.AbsoluteConstraints(302, 223, 103, 30));

        T.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Patient_ID", "Name", "Address", "NIC_No", "Telephone_No", "Gender", "Date_of_Birth", "Age"
            }
        ));
        jScrollPane1.setViewportView(T);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(166, 359, 630, 148));

        jButton1.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(0, 0, 153));
        jButton1.setText("ADD");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 320, -1, -1));

        jButton2.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jButton2.setForeground(new java.awt.Color(0, 0, 153));
        jButton2.setText("EDIT");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 320, -1, -1));

        jButton3.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jButton3.setForeground(new java.awt.Color(0, 0, 153));
        jButton3.setText("DELETE");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 320, -1, -1));
        getContentPane().add(D, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 270, 110, 30));

        jButton5.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jButton5.setForeground(new java.awt.Color(0, 0, 153));
        jButton5.setText("View");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 320, -1, -1));

        jButton6.setFont(new java.awt.Font("Serif", 3, 14)); // NOI18N
        jButton6.setForeground(new java.awt.Color(0, 0, 153));
        jButton6.setText("SEARCH");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 320, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents
    private void pActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_pActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_pActionPerformed
    abstract class Add {
        public abstract void updateTable();
    }
    class table extends Add {
    @Override
    public void updateTable(){
        try(Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdc", "root", ""))
        {
        Statement st=con.createStatement();
        String sql= "select* from patient";
        ResultSet rs=st.executeQuery(sql);
        //JOptionPane.showMessageDialog(null,rs.getString(1));
        while(rs.next())
        {
        String ID=rs.getString("Patient_ID");
        String NA=rs.getString("Name");
        String AD=rs.getString("Address");
        String NI=rs.getString("NIC_No");
        String TE=rs.getString("Telephone_No");
        String GE=rs.getString("Gender");
        String DA=rs.getString("Date_of_Birth");
        String AG=rs.getString("Age");
        String tbData[]={ID,NA,AD,NI,TE,GE,DA,AG};
        DefaultTableModel tbModel=(DefaultTableModel)
        T.getModel();
        tbModel.addRow(tbData);}
     }
      catch (Exception ex)
        {
        JOptionPane.showMessageDialog(null,ex);
        } 
    }
    }
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        try(Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdc", "root", ""))
        {
        PreparedStatement insert = con.prepareStatement("insert into patient(Patient_ID, Name, Address, NIC_No, Telephone_No, Gender, Date_of_Birth, Age) values (?,?,?,?,?,?,?,?)");
        insert.setString(1, p.getText());
        insert.setString(2, n.getText());
        insert.setString(3,a.getText());
        insert.setString(4,c.getText());
        insert.setString(5,t.getText());
        insert.setString(6,g.getSelectedItem()+ "");
        insert.setString(7,D.getText());
        insert.setString(8,e.getText());   
        insert.execute();
        JOptionPane.showMessageDialog(this, p.getText()+" Record will insert");
        p.setText("");
        n.setText("");
        a.setText("");
        c.setText("");
        t.setText("");
        g.setSelectedItem("Male");
        D.setText("");
        e.setText(""); 
        {
        Statement st=con.createStatement();
        String sql= "select* from patient";
        ResultSet rs=st.executeQuery(sql);
        //JOptionPane.showMessageDialog(null,rs.getString(1));
        while(rs.next())
        {
        String ID=rs.getString("Patient_ID");
        String NA=rs.getString("Name");
        String AD=rs.getString("Address");
        String NI=rs.getString("NIC_No");
        String TE=rs.getString("Telephone_No");
        String GE=rs.getString("Gender");
        String DA=rs.getString("Date_of_Birth");
        String AG=rs.getString("Age");
        String tbData[]={ID,NA,AD,NI,TE,GE,DA,AG};
        DefaultTableModel tbModel=(DefaultTableModel)
        T.getModel();
        tbModel.addRow(tbData);}
        
        //updateTable();
        con.close();
        } 
        } 
        catch (Exception ex)
        {
        JOptionPane.showMessageDialog(null,ex);
        }    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:          
        int E = JOptionPane.showConfirmDialog(null, "Are you sure you want to update?","Update Record",JOptionPane.YES_NO_OPTION);
        if(E==0){
           
            try (Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdc", "root", "")) {

                String value1 = p.getText();
                String value2 = n.getText();
                String value3 = a.getText();
                String value4 = c.getText();
                String value5 = t.getText();
                String value6 = (String) g.getSelectedItem();
                String value7 = D.getText();
                String value8 = e.getText();
                


                String sql= "update patient set Patient_ID='"+value1+"',Name='"+value2+"', Address='"+value3+"', "
                        + "NIC_No='"+value4+"',Telephone_No='"+value5+"',Gender='"+value6+"',Date_of_Birth='"+value7+"',Age= '"+value8+"'"+ "where Patient_ID='"+value1+"' ";

                pst=con.prepareStatement(sql);
                pst.execute();
                JOptionPane.showMessageDialog(null, "Record Updated");

            }catch(Exception e){
                JOptionPane.showMessageDialog(null, e);
            }
            
          
            finally {

                try{
                    rs.close();
                    pst.close();

                }
                catch(Exception e){

                }
            }
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        try(Connection con=DriverManager.getConnection("jdbc:mysql://localhost:3306/fdc", "root", "")) {
        PreparedStatement Delete = con.prepareStatement("DELETE FROM patient WHERE Patient_ID = ?");
        Delete.setString(1, p.getText());
        Delete.execute();
        JOptionPane.showMessageDialog(this, p.getText()+" Record will Delete in the Database");
        p.setText("");
        n.setText("");
        a.setText("");
        c.setText("");
        t.setText("");
        g.setSelectedItem("Male");
        D.setText("");
        e.setText(""); 
        con.close();
        } catch (SQLException ex) { 
        JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        // TODO add your handling code here:
        Appointment A = new Appointment();
        A.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel4MouseClicked

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
        // TODO add your handling code here:
        Staff u = new Staff();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel7MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel7MouseClicked
        // TODO add your handling code here:
        Doctor u = new Doctor();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel7MouseClicked

    private void jLabel8MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel8MouseClicked
        // TODO add your handling code here:
        Room u = new Room();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel8MouseClicked

    private void jLabel9MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel9MouseClicked
        // TODO add your handling code here:
        Payment u = new Payment();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel9MouseClicked
 
    private void jLabel10MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel10MouseClicked
        // TODO add your handling code here:
        ADlogin u = new ADlogin();
        u.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel10MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        // TODO add your handling code here:
        Patient p = new Patient();
        p.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    try (Connection con=DriverManager.getConnection ("jdbc:mysql://localhost:3306/fdc", "root", ""))
    {
    Statement st=con.createStatement();
    String sql= "select* from Patient";
    ResultSet rs=st.executeQuery(sql);
    //JOptionPane.showMessageDialog(null,rs.getString(1));
    while(rs.next())
    {
        String ID=rs.getString("Patient_ID");
        String NA=rs.getString("Name");
        String AD=rs.getString("Address");
        String NI=rs.getString("NIC_No");
        String TE=rs.getString("Telephone_No");
        String GE=rs.getString("Gender");
        String DA=rs.getString("Date_of_Birth");
        String AG=rs.getString("Age");
 
        String tbData[]={ID,NA,AD,NI,TE,GE,DA,AG};
    DefaultTableModel tbModel=(DefaultTableModel)
    T.getModel();
 
    tbModel.addRow(tbData);
    }
    con.close();
    } 
    catch (Exception ex)
        {
        JOptionPane.showMessageDialog(null,ex);
        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
        try { 
            String str = p.getText(); 
            Connection con = DriverManager.getConnection("jdbc:mysql://localhost:3306/fdc","root",""); 
            PreparedStatement st = con.prepareStatement("select * from patient where Patient_ID=?"); 
            st.setString(1, str); 
            //Excuting Query 
            ResultSet rs = st.executeQuery(); 
            if (rs.next()) { 
                String s = rs.getString(1); 
                String s1 = rs.getString(2); 
                String s2 = rs.getString(3); 
                String s3 = rs.getString(4);
                String s4 = rs.getString(5);
                String s5 = rs.getString(6);
                String s6 = rs.getString(7);
                String s7 = rs.getString(8);
                //Sets Records in TextFields. 
                p.setText(s);
                n.setText(s1);
                a.setText(s2);
                c.setText(s3);
                t.setText(s4);
                g.setSelectedItem(s5);
                D.setText(s6);
                e.setText(s7);
            } else { 
                JOptionPane.showMessageDialog(null, "ID not Found"); 
            } 
            //Create Exception Handler 
        } catch (Exception ex) { 
            System.out.println(ex); 
        }
    }//GEN-LAST:event_jButton6ActionPerformed
    
   
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Patient.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Patient().setVisible(true);
                Patient p1=new Patient();
               
                
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField D;
    private javax.swing.JTable T;
    private javax.swing.JTextField a;
    private javax.swing.JTextField c;
    private javax.swing.JTextField e;
    private javax.swing.JComboBox<String> g;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField n;
    private javax.swing.JTextField p;
    private javax.swing.JTextField t;
    // End of variables declaration//GEN-END:variables
}
